<a href="https://colab.research.google.com/github/Julianfried/Fundamentos-de-datos/blob/main/Clase1_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicios SQL I:

**DML:**
1. Ingresar dos nuevos clientes en la tabla Customers.
2. Actualizar el valor de la orden con order_id 5 a $200.
3. Eliminar uno de los clientes agregados a la tabla Customers.
4. Insertar una orden y su envio.

**DDL:**


1. Calcular la cantidad de ventas realizadas en el 2022.
2. Retornar la fecha de la primera venta registrada.
3. Retornar la venta de mayor dinero de cada cliente que tenga ventas.
4. Retornar la cantidad de envios a cada ciudad que no sea Belgrano.
5. Calcular la cantidad de dias activos que tiene cada cliente que aún no se han dado de baja.
6. Calcular el promedio de cantidad de dias activos que tienen los clientes que aún no se han dado de baja.
7. Retornar la cantidad de envios realizados entre enero y junio del 2022 para Mar del Plata.
8. Retornar la cantidad gastada por cliente con sus nombres para aquellos clientes que hayan gastado mas de $20.

In [ ]:
%sql INSERT INTO humai.Orders VALUES (7,5,'10/06/2022',500);

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [1]:
# install
!apt install postgresql postgresql-contrib &>log
!service postgresql start
!sudo -u postgres psql -c "CREATE USER root WITH SUPERUSER"
# set connection
%load_ext sql
%config SqlMagic.feedback=False
%config SqlMagic.autopandas=True
%sql postgresql+psycopg2://@/postgres

 * Starting PostgreSQL 12 database server
   ...done.
CREATE ROLE

In [2]:
%sql CREATE SCHEMA IF NOT EXISTS humai

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [4]:

%sql CREATE TABLE IF NOT EXISTS humai.Customers (customer_id INT NOT NULL, customer_name VARCHAR(50) NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE, PRIMARY KEY (customer_id));

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [5]:
%sql CREATE TABLE IF NOT EXISTS humai.Orders (order_id INT NOT NULL, customer_id INT NOT NULL, order_date DATE NOT NULL, order_price DECIMAL(8,2), PRIMARY KEY (order_id), FOREIGN KEY (customer_id) REFERENCES humai.Customers(customer_id));

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [6]:
%sql CREATE TABLE IF NOT EXISTS humai.Shipments ( shipment_id INT NOT NULL, order_id INT NOT NULL, shipment_date DATE NOT NULL, shipment_city VARCHAR(50), PRIMARY KEY (shipment_id), FOREIGN KEY (order_id) REFERENCES humai.Orders(order_id));

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [7]:
%sql INSERT INTO humai.Customers VALUES (1, 'Eugenio', '08/21/1998', Null), (2, 'Mario', '05/05/2005', Null), (3, 'Pedro', '03/08/2020', '02/05/2022')

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [8]:
%sql INSERT INTO humai.Orders VALUES (1, 1, '06/05/2022', 45), (2, 1, '06/05/2021', 60), (3, 1, '06/06/2022', 70), (4, 2, '01/05/2022', 5), (5, 3, '06/10/2022', 145), (6, 3, '03/02/2022', 2);

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [9]:
%sql INSERT INTO humai.Shipments VALUES (1, 1, '06/06/2022', 'Belgrano'), (2, 2, '06/06/2021', 'Mar del Plata'), (3, 3, '06/10/2022', 'Belgrano'), (4, 4, '02/05/2022', 'San Isidro'), (5, 5, '06/15/2022', 'Belgrano'), (6, 6, '03/05/2022', 'Mar del Plata');

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [59]:
%sql SELECT * FROM humai.Orders;

 * postgresql+psycopg2://@/postgres

   order_id  customer_id  order_date order_price
0         1            1  2022-06-05       45.00
1         2            1  2021-06-05       60.00
2         3            1  2022-06-06       70.00
3         4            2  2022-01-05        5.00
4         6            3  2022-03-02        2.00
5         5            3  2022-06-10      200.00
6         7            5  2022-10-06      500.00

In [11]:
%sql INSERT INTO humai.Customers VALUES (4, 'Juan', '10/05/2022', Null),(5, 'Riki', '10/05/2026', '05/05/2027')

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [14]:
%sql UPDATE humai.Orders SET order_price = 200 WHERE order_id = 5;

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [16]:
%sql DELETE FROM humai.Customers WHERE customer_id = 4;

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [22]:
%sql INSERT INTO humai.Orders VALUES (7,5,'10/06/2022',500);

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [24]:
%sql INSERT INTO humai.Shipments VALUES (7,7,'10/06/2022','Rusia');

 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [26]:
%sql SELECT count(*) AS "Ventas en 2022" FROM humai.Orders WHERE EXTRACT(YEAR FROM order_date) = 2022;

 * postgresql+psycopg2://@/postgres

   Ventas en 2022
0               6

In [28]:
%sql SELECT order_date AS "Fecha de primera venta" FROM humai.Orders ORDER BY order_date ASC LIMIT 1;

 * postgresql+psycopg2://@/postgres

  Fecha de primera venta
0             2021-06-05

In [44]:
%sql SELECT customer_id, MAX(order_price) as "Mayor Venta" FROM humai.Orders  GROUP BY customer_id;

 * postgresql+psycopg2://@/postgres

   customer_id Mayor Venta
0            3      200.00
1            5      500.00
2            2        5.00
3            1       70.00

In [46]:
%sql SELECT shipment_city, count(shipment_id) as "n_shipments" FROM humai.Shipments WHERE shipment_city != 'Belgrano' GROUP BY shipment_city;

 * postgresql+psycopg2://@/postgres

   shipment_city  n_shipments
0  Mar del Plata            2
1          Rusia            1
2     San Isidro            1

In [49]:
%sql SELECT customer_name, CAST(date_part('day', NOW() - fecha_inicio) AS INTEGER) AS active_days FROM humai.Customers;

 * postgresql+psycopg2://@/postgres

  customer_name  active_days
0       Eugenio         8982
1         Mario         6533
2         Pedro         1112
3          Riki        -1289

In [51]:
%sql SELECT AVG(CAST(date_part('day', NOW() - fecha_inicio) AS INTEGER)) as "avg_active_days" FROM humai.Customers WHERE fecha_fin IS Null

 * postgresql+psycopg2://@/postgres

         avg_active_days
0  7757.5000000000000000

In [56]:
%sql SELECT COUNT(shipment_id) as n_shipments_mqd FROM humai.Shipments WHERE shipment_date >= '2022-01-01' AND shipment_date <= '2022-05-31' AND shipment_city = 'Mar del Plata';

 * postgresql+psycopg2://@/postgres

   n_shipments_mqd
0                1

In [58]:
%sql SELECT customer_name, SUM(order_price) AS total_order_price FROM humai.Customers INNER JOIN humai.Orders ON humai.Customers.customer_id = humai.Orders.customer_id WHERE order_price > 20 GROUP BY humai.Customers.customer_id;

 * postgresql+psycopg2://@/postgres

  customer_name total_order_price
0         Pedro            200.00
1          Riki            500.00
2       Eugenio            175.00